//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HuaHaoERP.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HuaHaoERP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE &quot;T_Orders_Processors&quot; (
        ///&quot;Guid&quot;  Guid NOT NULL,
        ///&quot;OrderNumber&quot;  TEXT,
        ///&quot;ProcessorsID&quot;  Guid,
        ///&quot;DeliveryDate&quot;  DateTime,
        ///&quot;OrderDate&quot;  DateTime,
        ///&quot;DeleteMark&quot;  DateTime,
        ///&quot;Obligate1&quot;  TEXT,
        ///&quot;Obligate2&quot;  TEXT,
        ///PRIMARY KEY (&quot;Guid&quot; ASC)
        ///);
        ///CREATE TABLE &quot;T_Orders_ProcessorsDetails&quot; (
        ///&quot;Guid&quot;  Guid NOT NULL,
        ///&quot;Order&quot;  Guid,
        ///&quot;Product&quot;  Guid,
        ///&quot;NumberOfItems&quot;  INTEGER,
        ///&quot;Quantity&quot;  INTEGER,
        ///&quot;Unit&quot;  TEXT,
        ///&quot;Remark&quot;  TEXT,
        ///&quot;Obligate1&quot;  TEXT,
        ///&quot;Obligate2&quot;  TEXT,
        ///PRIMARY KEY (&quot;Guid&quot; ASC)
        ///);
        ///CREAT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DataBase {
            get {
                return ResourceManager.GetString("DataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] 外加工对账单 {
            get {
                object obj = ResourceManager.GetObject("外加工对账单", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
